# This is a basic workflow to build and deploy your open textbook with Bookdown.

on:
  push:
    branches: 
      - main

# Courtesy of _Github actions with R_, available: https://ropenscilabs.github.io/actions_sandbox/

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install R Markdown and Bookdown packages
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Install TinyTeX
        run: Rscript -e 'tinytex::install_tinytex()'
      - name: Build Book
        run: |
          set -ev
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./_book # The folder the action should deploy.
